name: discipline_plus
description: "DisciplinePlus is a productivity app designed to help you build strong habits and master self-discipline. Set daily goals, track your progress, and stay motivated with smart reminders and fun daily memory challenges."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sliding_up_panel: ^2.0.0+1
  just_audio: ^0.9.46
  wakelock_plus: ^1.2.11
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  pull_to_refresh: ^2.0.0
  intl: ^0.20.2
  excel: ^4.0.6
  rxdart: ^0.28.0




dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:


  uses-material-design: true


  assets:
    - assets/audio/
#    - assets/images/lc.jpg


